services:
   MkdocsApply:
       image: imageformkdocs:2.0.2
       volumes:
         - default
       networks:
         net:
            ipv4_address: 172.17.0.5
       deploy:
           resources:
              limits:
                 cpus: '0.1'
                 memory: 1000M
networks:
   net:
     driver: bridge
     ipam:
       config:
         - subnet: 172.17.0.0/16
           gateway: 172.17.0.1
