FROM python:3.12.3-alpine
                
LABEL Role=site
        
LABEL Server=Server
                
RUN pip3 install mkdocs
                
RUN mkdir my-project
             
RUN mkdocs new my-project

CMD mkdocs serve
                
CMD mkdocs build

WORKDIR my-project

CMD python3 -m http.server 8088

