
FROM wordpress
                      
RUN mkdir /wordpress
                      
WORKDIR /wordpress
                      
LABEL Role=site
        
LABEL Server=Server
                     
LABEL data=mysql-data 
