services:
   AppWordpress:
      image:ourwordpress-imageforwordpress:2.0.2
      environment:
        WORDPRESS_DB_HOST:databases
        WORDPRESS_DB_USER:root
        WORDPRESS_DB_PASSWORD:passwd
        WORDPRESS_DB_NAME:database
      volumes:
          - default
      depends_on:
          - databases
      networks:
          net:
            ipv4_address:172.17.0.4
      deploy:
           resources:
              limits:
                 cpus: '0.1'
                 memory: 1000M
   databases:
      image:mysql:8.0
      environment:
          MYSQL_DATABASE:database
          MYSQL_USER:root
          MYSQL_PASSWORD:passwd
      volumes:
         - default
      networks:
          net:
            ipv4_address:172.17.0.4
      deploy:
           resources:
              limits:
                 cpus: '0.1'
                 memory: 1000M
networks:
   net:
     driver:bridge
     ipam:
       config:
         - subnet: 172.17.0.0/16
           gateway: 172.17.0.1
