services:
    WEB_proxy:
        image: imageforproxy:2.0.2
        container_name: proxy
        ports:
          - "8091:80"
        volumes:
          - ./proxy-ap:/srv/www
          - ./apache2.conf:/etc/apache2/apache2.conf
        networks:
           proxy-net:
               ipv4_address: 172.17.0.2
        deploy:
          resources:
            limits:
              cpus: '0.1'
              memory: 1000M
networks:
  proxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.17.0.0/16
          gateway: 172.17.0.1
