services:
    Apply-Group:
        image:imageforsite:2.0.2
        container_name:python-server
        volumes:
          . /site-groupe:/Site-apply
        networks:
            python-net:
               ipv4_address:172.17.0.3
        deploy:
           resources:
              limits:
                 cpus:'0.1'
                 memory: 1000M
networks:
   python-net:
    driver:bridge
    ipam:
      config:
          subnet:172.17.0.0/16
          gateway:172.17.0.1
